---
title: "Seurat Simulated Data DESTVI"
output: html_notebook
---

```{r}
library(Seurat)
library(SeuratData)
library(ggplot2)
library(patchwork)
library(dplyr)
library(anndata)
library(Matrix)
library("SeuratDisk")
library(dplyr)

```
```{r}
Convert("/Users/tanushkumar/Dropbox/ST_Project/SimulatedData/st_simu.h5ad", dest="h5Seurat", overwrite=TRUE)
st<-LoadH5Seurat("/Users/tanushkumar/Dropbox/ST_Project/SimulatedData/st_simu.h5Seurat")
sc<-read_h5ad("/Users/tanushkumar/Dropbox/ST_Project/SimulatedData/sc_simu.h5ad")
sc<-as.matrix(sc)
```
```{r}
st<-RenameAssays(st, RNA="Spatial")
plot1 <- VlnPlot(st, features = "nCount_Spatial", pt.size = 0.1) + NoLegend()
plot1
```
```{r}
st<-SCTransform(st, assay="Spatial", verbose=FALSE)
st<-RunPCA(st,assay="SCT",verbose=FALSE)
st <- FindNeighbors(st, reduction = "pca", dims = 1:30)
st <- FindClusters(st,verbose=FALSE)
st<-RunUMAP(st,reduction="pca", dims=1:30)
DimPlot(st, reduction="umap", label=TRUE)
```
```{r}
transpose_dgRMatrix <- function(inmat) {
  if(class(inmat) != 'dgRMatrix')
    stop('inmat is not of class dgRMatrix')
  out <- new('dgCMatrix',
             i=inmat@j,
             p=inmat@p,
             x=inmat@x,
             Dim=rev(inmat@Dim),
             Dimnames=rev(inmat@Dimnames)
  )
  out
}      

sc<-transpose_dgRMatrix(sc)
```
```{r}
sc <- CreateSeuratObject(counts = sc)
sc<-SCTransform(sc,ncells=3000,verbose=FALSE)
sc<-RunPCA(sc,verbose=FALSE)
sc<-RunUMAP(sc,dims=1:30)
```
```{r}
annotations<-read.csv("/Users/tanushkumar/Dropbox/ST_Project/SimulatedData/annots.csv")
annotations$cell_type<-as.character(annotations$cell_type)
sc$subclass<-annotations$cell_type
DimPlot(sc,group.by = "subclass",label=TRUE)
```
```{r}
anchors <- FindTransferAnchors(reference = sc, query = st, normalization.method = "SCT")
output<- TransferData(anchorset = anchors, refdata =sc$subclass)
```
```{r}
output<-as.matrix(output[,-1])
#to_csv(output,"output_Seurat.csv")
#write.csv(test,"/Users/tanushkumar/Dropbox/ST_Project/output_Seurat.csv")

```



